### ISSUE TITLE
AuthorizationCodeCredentials throws an exception

### ISSUE THREAD

**Issue by EinfachEinAlex** [spotify-web-api-java/spotify-web-api-java#257]
The class "AuthorizationCodeCredentials" throws an exception when you run the following code

`            AuthorizationCodeRequest authorizationCodeRequest = spotifyApi.authorizationCode(token)
                    .build();
            final AuthorizationCodeCredentials authorizationCodeCredentials = authorizationCodeRequest.execute();`

The following exception is the result: Unsupported cookie policy: default
__Caused by: org.apache.http.HttpException: Unsupported cookie policy: default
	at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:150)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:131)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:193)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	... 17 more

**Comment by dargmuesli** [comment]
I cannot reproduce this error using the most recent version. Will reopen once a reproduction is possible. Which version are you using? Which OS?

Kinda offtopic but: you might wanna rethink your website's wording.
