### ISSUE TITLE
UnsupportedOperationException: JsonObject (getAsInt duration_ms)

### ISSUE THREAD

**Issue by Selbi182** [spotify-web-api-java/spotify-web-api-java#381]
I've been receiving the following error when trying to grab a playlist recently:
```
java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsInt(JsonElement.java:231)
	at se.michaelthelin.spotify.model_objects.specification.Track$JsonUtil.createModelObject(Track.java:564)
	at se.michaelthelin.spotify.model_objects.specification.PlaylistTrack$JsonUtil.createModelObject(PlaylistTrack.java:161)
	at se.michaelthelin.spotify.model_objects.specification.PlaylistTrack$JsonUtil.createModelObject(PlaylistTrack.java:145)
	at se.michaelthelin.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObjectArray(AbstractModelObject.java:78)
	at se.michaelthelin.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObjectPaging(AbstractModelObject.java:126)
	at se.michaelthelin.spotify.model_objects.specification.Playlist$JsonUtil.createModelObject(Playlist.java:449)
	at se.michaelthelin.spotify.model_objects.specification.Playlist$JsonUtil.createModelObject(Playlist.java:392)
	at se.michaelthelin.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObject(AbstractModelObject.java:60)
	at se.michaelthelin.spotify.requests.data.playlists.GetPlaylistRequest.execute(GetPlaylistRequest.java:38)
```

Taking a look at the duration_ms field in the code, it appears that one is no longer returning an integer but rather a weird JSON object?

![grafik](https://github.com/spotify-web-api-java/spotify-web-api-java/assets/8850085/85176aa9-c578-4788-b7b7-75b2a2e4e97e)

I don't know if Spotify silently changed stuff again, but this is breaking.

**Comment by Selbi182** [comment]
@dargmuesli Is this good enough for a PR?

    .setDurationMs(
      hasAndNotNull(jsonObject, "duration_ms")
        ? getDurationMsFixed(jsonObject)
        : null)

      private static int getDurationMsFixed(JsonObject jsonObject) {
        JsonElement durationMs = jsonObject.get("duration_ms");
        if (durationMs.isJsonPrimitive()) {
          return durationMs.getAsInt();
        } else {
          return durationMs.getAsJsonObject().get("totalMilliseconds").getAsInt();
        }
      }

It's kinda hacky, but I really don't know how to make this cleaner either...

**Comment by dargmuesli** [comment]
... Spotify at it again :roll_eyes: one would expect an api like theirs not having those deviations from its specification.

As you might've read in other issues this repo follows the practice of understanding the documentation as source of truth, which would make the issue an upstream bug which would not necessarily see a fix included in this repo's source. But things being things allow for exceptions to be possible I guess. I've subscribed to [your upstream bug report](https://community.spotify.com/t5/Spotify-for-Developers/duration-ms-includes-nonsense-JSON/m-p/5753768/) so adding a workaround in this repo is fine for me; we can remove it once there is advice by Spotify on how to proceed.

Please make sure to add documentation to this workaround explaining and linking the resources mentioning the necessity for the workaround :heart:

**Comment by Selbi182** [comment]
PR is up!
